In [1]:
# numpy version
import numpy
numpy.__version__

'1.11.3'

In [1]:
# 创建
import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
# ndarray的维度：shape属性
a.shape
b.shape
c.shape

(3, 4)

In [4]:
# 修改ndarray的轴的长度，不改变数组元素在内存中的位置，只是改变轴的大小
c.shape = 4,3
c

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  7,  7],
       [ 8,  9, 10]])

In [5]:
# 轴的长度设置-1，自动计算
c.shape = 2,-1
c

array([[ 1,  2,  3,  4,  4,  5],
       [ 6,  7,  7,  8,  9, 10]])

In [6]:
# reshape()创建指定形状的新数组，而原数组的形状保持不变
d = a.reshape((2,2))
d,a
# 实际上数组a和d共享数据存储空间，修改其中任意一个数组的元素都会同时修改另一个数组的内容

(array([[1, 2],
        [3, 4]]), array([1, 2, 3, 4]))

In [7]:
# 元素类型
c.dtype

dtype('int64')

In [8]:
# dtype参数在创建数组时指定元素类型
ai32 = np.array([1,2,3,4],dtype=np.int32)
af = np.array([1,2,3,4],dtype=float)
ac = np.array([1,2,3,4],dtype=complex)
ai32.dtype,af.dtype,ac.dtype

(dtype('int32'), dtype('float64'), dtype('complex128'))

In [11]:
[key for key,value in np.typeDict.items() if value is np.float64]

[12, 'd', 'float64', 'float_', 'float', 'f8', 'double', 'Float64']

In [12]:
# typeDict存储的所有类型
set(np.typeDict.values())

{numpy.object_,
 numpy.bool_,
 numpy.string_,
 numpy.unicode_,
 numpy.void,
 numpy.int8,
 numpy.int16,
 numpy.int32,
 numpy.int64,
 numpy.int64,
 numpy.uint8,
 numpy.uint16,
 numpy.uint32,
 numpy.uint64,
 numpy.uint64,
 numpy.float16,
 numpy.float32,
 numpy.float64,
 numpy.float128,
 numpy.datetime64,
 numpy.timedelta64,
 numpy.complex64,
 numpy.complex128,
 numpy.complex256}

In [13]:
c.dtype.type

numpy.int64

In [14]:
# 16位的符号整数对象，取值范围有限，溢出
a = np.int16(200)
a*a

/Users/cyq/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:3: RuntimeWarning: overflow encountered in short_scalars
  app.launch_new_instance()


-25536

In [15]:
#  比较Numpy的数值对象的运算速度比Python的内置类型的运算速度慢很多
v1 = 3.14
v2 = np.float64(v1)
%timeit v1*v1
%timeit v2*v2

The slowest run took 28.08 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 67.9 ns per loop
The slowest run took 28.48 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 109 ns per loop


In [16]:
# astype()方法可以对数组的元素类型进行转换
t1 = np.array([1,2,3,4],dtype=np.float)
t2 = np.array([1,2,3,4],dtype=np.complex)
t3 = t1.astype(np.int32)
t4 = t2.astype(np.complex64)

In [18]:
t3.dtype,t3.shape,t4.dtype,t4.shape

(dtype('int32'), (4,), dtype('complex64'), (4,))

In [5]:
# 自动生成数组
np.arange(0,1,0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [6]:
np.linspace(0,1,10)

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ])

In [7]:
np.linspace(0,1,10,endpoint=False)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [8]:
# 创建等比数组
np.logspace(0,1,12,base=2,endpoint=False) # base是底数，默认是10

array([ 1.        ,  1.05946309,  1.12246205,  1.18920712,  1.25992105,
        1.33483985,  1.41421356,  1.49830708,  1.58740105,  1.68179283,
        1.78179744,  1.88774863])

In [9]:
# empty()只分配内存，不进行初始化
np.empty((2,3),np.int)

array([[8070450532247928832, 8070450532247928832,          4451598339],
       [         4569009976,                   9,     844424930131968]])

In [10]:
np.zeros(4,np.int),np.ones(5,np.int)

(array([0, 0, 0, 0]), array([1, 1, 1, 1, 1]))

In [11]:
np.full(4,np.pi)

array([ 3.14159265,  3.14159265,  3.14159265,  3.14159265])

In [12]:
a = np.array([[1,2,3],[4,2,1]])
b = np.zeros_like(a)
b

array([[0, 0, 0],
       [0, 0, 0]])

In [13]:
s = 'abcdefgh'
np.fromstring(s,dtype=np.int8)  # 输出刚好对应每个字符的ASCII码

array([ 97,  98,  99, 100, 101, 102, 103, 104], dtype=int8)

In [3]:
def func(i,j):
    return (i+1)*(j+1)
np.fromfunction(func,(9,9))

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
       [  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.],
       [  3.,   6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.],
       [  4.,   8.,  12.,  16.,  20.,  24.,  28.,  32.,  36.],
       [  5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.],
       [  6.,  12.,  18.,  24.,  30.,  36.,  42.,  48.,  54.],
       [  7.,  14.,  21.,  28.,  35.,  42.,  49.,  56.,  63.],
       [  8.,  16.,  24.,  32.,  40.,  48.,  56.,  64.,  72.],
       [  9.,  18.,  27.,  36.,  45.,  54.,  63.,  72.,  81.]])

In [4]:
# 存取元素和列表的方式相同
# （1）切片方式
a = np.arange(10)
a[5],a[3:5],a[:5],a[:-2]

(5, array([3, 4]), array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4, 5, 6, 7]))

In [5]:
a[1:-1:2],a[:],a[::-1],a[5:1:-2]

(array([1, 3, 5, 7]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]),
 array([5, 3]))

In [6]:
# 下标修改元素的值
a[2:4]=100,101
a   # 注意，通过切片获取的新的数组是原始数组的一个视图

array([  0,   1, 100, 101,   4,   5,   6,   7,   8,   9])

In [4]:
# （2）整数列表
import numpy as np
a = np.arange(10,1,-1)
b = a[[3,3,1,8]]
c = a[[1,2,3,-3]]
a,b,c

(array([10,  9,  8,  7,  6,  5,  4,  3,  2]),
 array([7, 7, 9, 2]),
 array([9, 8, 7, 4]))

In [5]:
b[2] = 100
a,b  # 注意，通过整数列表获得的数组与原数组不共享

(array([10,  9,  8,  7,  6,  5,  4,  3,  2]), array([  7,   7, 100,   2]))

In [13]:
# （3）整数数组
d = a[np.array([8,1,2])]
a,d

(array([10,  9,  8,  7,  6,  5,  4,  3,  2]), array([2, 9, 8]))

In [15]:
# (4)布尔数组
a = np.arange(5,0,-1)
d = a[np.array([True,False,True,False,True])]
a,d

(array([5, 4, 3, 2, 1]), array([5, 3, 1]))

In [16]:
# (5)布尔列表
a[[True,False,True,True,False]]

/Users/cyq/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: FutureWarning: in the future, boolean array-likes will be handled as a boolean array index
  from ipykernel import kernelapp as app


array([4, 5, 4, 4, 5])

In [17]:
x = np.random.randint(0,10,6)
x>5,x[x>5]

(array([False,  True, False, False, False, False], dtype=bool), array([7]))

In [3]:
# 多维数组
a = np.arange(0,60,10).reshape(-1,1) + np.arange(0,6)
a  # broadcast广播

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [20]:
# 利用元组作为下标,得到数组和原始数组共享数据
a[0,3:5],a[4:,4:],a[:,2]

(array([3, 4]), array([[44, 45],
        [54, 55]]), array([ 2, 12, 22, 32, 42, 52]))

In [24]:
a[::2]

array([[ 0,  1,  2,  3,  4,  5],
       [20, 21, 22, 23, 24, 25],
       [40, 41, 42, 43, 44, 45]])

In [25]:
 x= np.array([1,2,3,4])

In [30]:
idx = slice(None,None,2),slice(2,None)
idx  # idx等价于::2,2:

(slice(None, None, 2), slice(2, None, None))

In [35]:
# s_是IndexExpression类的一个对象
np.s_[::2,2:]

(slice(None, None, 2), slice(2, None, None))

In [15]:
a = np.arange(0,60,10).reshape(-1,1) + np.arange(0,6)

In [38]:
a[(0,1,2,3),(1,2,3,4)]

array([ 1, 12, 23, 34])

In [4]:
a[3:,[0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [40]:
mask = np.array([1,0,1,02,0,1],dtype=np.bool)
a[mask,2]

array([ 2, 22, 52])

In [31]:
# 当下标长度小于数组的维数时，剩余各轴所对应的下标是 :
a[[1,2],:],'\r',a[[1,2]]

(array([[10, 11, 12, 13, 14, 15],
        [20, 21, 22, 23, 24, 25]]), '\r', array([[10, 11, 12, 13, 14, 15],
        [20, 21, 22, 23, 24, 25]]))

In [34]:
# 当所有轴都用形状相同的整数数组作为下标时，得到的数组和下标数组的形状相同。
x = np.array([[0,1],[2,3]])
y = np.array([[-1,-2],[-3,-4]])
a[x]

array([[[ 0,  1,  2,  3,  4,  5],
        [10, 11, 12, 13, 14, 15]],

       [[20, 21, 22, 23, 24, 25],
        [30, 31, 32, 33, 34, 35]]])

In [35]:
a[x,y]
# ？？？二维数组根据下标取值得到高维数组好晕。。。。。。。

array([[ 5, 14],
       [23, 32]])

In [40]:
# 结构数组
persontype = np.dtype({'names':['name','age','weight'],'formats':['S30','i','f']},align=True)
a = np.array([("Zhang",32,75.5),("Wang",24,65.2)],dtype=persontype)

In [45]:
a.dtype
a[0],a[0].dtype,a[0]["age"]

(('Zhang', 32, 75.5),
 dtype({'names':['name','age','weight'], 'formats':['S30','<i4','<f4'], 'offsets':[0,32,36], 'itemsize':40}, align=True),
 32)

In [46]:
# ufunc函数（universal function）
x = np.linspace(0,2*np.pi,10)
y = np.sin(x)
y

array([  0.00000000e+00,   6.42787610e-01,   9.84807753e-01,
         8.66025404e-01,   3.42020143e-01,  -3.42020143e-01,
        -8.66025404e-01,  -9.84807753e-01,  -6.42787610e-01,
        -2.44929360e-16])